[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "lhapdfutils"
dynamic = ["version"]
description = "Various utilities for LHAPDF"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "dash>=2.18",
  #"lhapdf>=6.5.6",
  "numpy>=2.0",
  "plotly>=6.0",
  "lhagrid"
]

[project.scripts]
lhapdf-explorer = "lhapdfutils.explorer.app:main"
lhapdf-combine = "lhapdfutils.combine._cli:main"
lhapdf-scale = "lhapdfutils.scale._cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/lhapdfutils"]

[tool.hatch.version]
path = "src/lhapdfutils/__about__.py"


[project.urls]
Documentation = "https://github.com/APN-Pucky/lhapdfutils#readme"
Issues = "https://github.com/APN-Pucky/lhapdfutils/issues"
Source = "https://github.com/APN-Pucky/lhapdfutils"
